/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

/**
 * @file
 * Javascript to initialize singe date time library.
 */

(function ($, Drupal, drupalSettings) {

  /**
   * Attaches the single_datetime behavior.
   *
   * @type {Drupal~behavior}
   */
  Drupal.behaviors.override_single_datetime = {
    attach: function attach(context) {

      // Setting the current language for the calendar.
      var lang = drupalSettings.path.currentLanguage;

      $(context).find("input[data-single-date-time]").once("datePicker").each(function () {
        var input = $(this);

        // Get widget type.
        var widgetType = input.data("singleDateTime");

        // Get hour format - 12 or 24.
        var hourFormat = input.data("hourFormat");

        // Get first day in week from Drupal.
        var dayOfWeekStart = input.data("firstDay");

        // Default values (used for dates only).
        var format = "d-m-Y";
        var allowTimepicker = false;

        // Get disabled days.
        var disabledWeekDays = input.data("disableDays");

        // Get excluded dates.
        var disabledDates = input.data("excludeDate");

        // Get minimum date.
        var minDate = input.data("minDate");

        // Get maximum date.
        var maxDate = input.data("maxDate");

        // Get start year.
        var yearStart = input.data("yearStart");

        // Get end year.
        var yearEnd = input.data("yearEnd");

        // Set the hour format.
        var formatTime = hourFormat === "12h" ? "h:i A" : "H:i";

        var inline = input.data("inline");

        var mask = Boolean(input.data("mask"));

        var theme = input.data("datetimepickerTheme");

        // Default empty array. Only calculate later if field type
        // includes times.
        var allowTimes = [];

        // If is date & time field.
        if (widgetType === "datetime") {
          format = hourFormat === "12h" ? "Y-m-d h:i:s A" : "Y-m-d H:i:s";
          allowTimepicker = true;

          // Get minute granularity, and allowed hours.
          allowTimes = SingleDatetimeAllowTimes(input.data("allowedHours"), input.data("allowTimes"));
        }

        $("#" + input.attr("id")).datetimepicker({
          format: format,
          formatTime: formatTime,
          lazyInit: true,
          timepicker: allowTimepicker,
          todayButton: true,
          dayOfWeekStart: dayOfWeekStart,
          allowTimes: allowTimes,
          disabledWeekDays: disabledWeekDays,
          disabledDates: disabledDates,
          formatDate: "d.m.Y",
          inline: inline,
          mask: mask,
          minDate: minDate,
          maxDate: maxDate,
          yearStart: yearStart,
          yearEnd: yearEnd,
          theme: theme
        });
        // Explicitly set locale. Does not work with passed variable
        // in setttings above.
        $.datetimepicker.setLocale(lang);
      });
    }
  };
})(jQuery, Drupal, drupalSettings);